hackerspace-ntnu/website

wiki/templates/wiki/includes/render.html

Long lines of text makes it harder to focus while reading.
Optimal line length is between 50-75 letters according to
http://baymard.com/blog/line-length-readability
This fix defines a maximum width for the articles, to ensure lines stay
at least under 100 letters even for large monitors, while still keeping
some width for displaying large images etc.

Add max-width to wiki articles

---

website/views.py

Sorts events by start time and not creation time on the frontpage. Requested by LapOps

Sorting events correctly on the frontpage

---

website/settings.py

4mb unødvendig, material pakken er ikke nødvendig noe sted.

Remove material, unused

---

news/templates/news/event.html

Feil lenke i form gjør at ingen får registrert seg til events.

Hotfix wrong url for event registration

---

website/settings.py

Disallowed host errors are errors due to client misconfiguration and make no sense to log.

Disable all logging of disallowed hosts

---

news/templates/news/event.html

Fixes: #283 
Event med samme start/slutt-dato:
Event med ulik start/slutt-dato:

Display proper end/start dates if different

---

.travis.yml
website/templates/website/header.html

Grunnet dårlige Javascript calls og merkelig embedding system har jeg valgt å fjerne MazeMap embed og heller bare åpne i en ny fane.
Med MazeMap (PageSpeed)
Uten MazeMap (PageSpeed)
Åpenbart at MazeMap har sine utfordringer med både media og script
De har i tillegg ingen got leverage browser caching.

Fjern MazeMap API til fordel for hyperlink

---

news/templates/news/article.html
news/templates/news/event.html

Override ckeditor som injecter, ingen god måte å overstyre på i django-ckeditor så må bli i javascript.

Fix image scaling on smaller devices

---

files/models.py
news/templates/news/article.html
news/templates/news/event.html

Legg til OPG Metadata for bedre facebook linker og link previews generelt.

Add OpenGraph Metadata for prettier Facebook links

---

website/templates/website/index.html
website/views.py

Feature: #364 
Forkorter teksten trinnvis i et forsøk på å håndtere ulike skjermstørrelser:
- Large:
- Medium (større siden det nå er én kolonne i bredden):
- Small:

Added indicator for hidden internal events

---

news/static/news/css/news_style.css
news/templates/news/events.html
news/templates/news/internal_indicator.html
news/templates/news/news.html
news/views.py
website/templates/website/index.html
website/templates/website/internal_indicator.html
website/views.py

Extension of #438 as suggested by @camelgod 
Also introduced partial code-reuse with `internal_indicator.html` template and `indicator` variable in `/website` and `/news`.

Added internal indicator to /news, /events and articles in index 

---

news/templates/news/_event_admin_menu.html

Unregistered attendance before event start should not be punished with a devil emoji. Will now display a pending emoji as long as the event has not started

Added pending icon on event registrations before event start

---

website/templates/website/tos-returningls.html
website/views.py

Fixes #459 
Stores users path before TOS redirect in a temporary session variable. This is later accessed to return the user to their originally visited path.

Redirect TOS accept to originally visited path

---

website/templates/website/header.html

Before this change the admin menu item linked to an admin panel page that offered minimal functionality
With this change the menu item now links to the django admin panel at /admin

Replaced existing admin page link with admin panel link in header menu

---

userprofile/templates/userprofile/create_tos.html
userprofile/templates/userprofile/tos_detail.html
userprofile/views.py
website/templates/website/header.html
website/urls.py

Added create TOS button in TOS detail view.
When create TOS button is clicked the text form is initially filled with the text from the latest existing TOS. This emphasises that a TOS cannot be edited, only created, while still being able to keep as much text as wanted.

Added button to create TOS based on existing one

---

news/static/news/css/news_style.css
news/templates/news/_event_admin_menu.html
news/templates/news/attendee_form.html

- Event attendance list now consists of table-like rows with cell-like items (name and attendance status). This adds better support for long names that break into multiple lines on mobile.
- Attendee names now link to corresponding profile page
- Attendance status icons now link to /attended
- Also made som minor language enhancements in event view and /attended

Added better support for long names in event attendance list, and other attendance enhancements

---

website/urls.py

Since the old admin panel page has been replaced, it's natural to remove the associated urlpattern.

Removed urlpattern for the old admin panel page

---

userprofile/static/userprofile/css/skills_style.css
userprofile/static/userprofile/css/userprofile_style.css
userprofile/static/userprofile/js/display_skill.js
userprofile/templates/userprofile/profile.html
userprofile/templates/userprofile/skill_badges.html
userprofile/templates/userprofile/skill_description.html
userprofile/templates/userprofile/skills.html
userprofile/templates/userprofile/skills_category.html
userprofile/urls.py
userprofile/views.py

- Category info page displays information about a category (name and description) and a list of related skills.
- Prerequisites are now clickable on the `/skills` page. When clicked, the related skill is revealed inside the tabs and collapsible system.

Added category info page and skill prereq redirects

---

userprofile/static/userprofile/javascript/display_skill.js
userprofile/templates/userprofile/skills.html

- Skills on profile page can now be linked to with url (`../profile/<profile_id>/skills/<skill_id>`)
- Clicking through skills ignores browser history (back button will go to last page, not last clicked skill)
- Moved some inline scripts related to skill displaying into a related script file
- Fixed a bug relating to empty tabs

Improved linking to skills and moved inline scripts

---

news/models.py
news/static/news/css/news_style.css
news/templates/news/_event_admin_menu.html
userprofile/models.py

This is an alternative to #490 in response to feedback from @camelgod in #487. The profile names have now simply been hidden, but the overview of combinations is still provided:

Added individual combinations in allergies section

---

website/templates/website/footer.html

Including opening hours for the workshop and a link to our issue tracker. The GitHub link leads to the [issue format picker](https://github.com/hackerspace-ntnu/website/issues/new/choose). Also fixes cutoff on the NTNU IDI and KID logos on *extremely* small displays.
Closes #500

Footer improvements

---

userprofile/templates/userprofile/profile_list.html

Endret fra:
For å se enkel oversikt gruppers medlemmer, sjekk ut om oss siden.
Til:
For oversikt over gruppene og deres medlemmer, se Om oss

Oppdatert tekst på /members

---

.github/workflows/integration.yml

Integration test would not always run when recieving external pull requests. attempts to fix that.

Add `pull_request` trigger to integration

---

inventory/templates/inventory/inventory.html
website/context_processors.py
website/settings.py
website/templates/website/about.html
website/templates/website/footer.html
website/templates/website/header.html
website/templates/website/index.html

The [`360-A2-116`](https://use.mazemap.com/?v=1&campusid=1&sharepoitype=identifier&sharepoi=360-A2-116) ID should be more long-lived than the [`6379`](https://use.mazemap.com/#v=1&zlevel=2&center=10.404406,63.415418&zoom=18&sharepoitype=poi&sharepoi=6379&campuses=ntnu&campusid=1&utm_medium=url_scheme) POI ID that the "bit.ly" link points to, according to a support employee in MazeMap, who I contacted.
Also extracted the references to the link to a template context processor, which makes it easier to update the link in the future.

Add more permanent MazeMap link

---

news/views.py
website/views.py

Draft articles where visible as previous/next articles, as well as counted towards the internal articles count. They are now excluded from this.
(Also neutralized a useless variable 🤺)

Excluded drafts from prev/next articles and internal count

---

website/templates/website/rule_details.html

Fixed image styling on rule details pages. Related to #545 
Before:
After:

Enhanced rule details image styling

---

authentication/tests.py
requirements.txt

The 5.0.0 release of `social-auth-app-django` introduced [a breaking change](https://github.com/python-social-auth/social-app-django/pull/263) ([permalink](https://web.archive.org/web/20210831080835/https://github.com/python-social-auth/social-app-django/pull/263)) that removed a utility function used in one of our auth tests.
This has now been updated in line with the 5.0.0 change.
The requirement in question has also been updated with a fixed version number to possibly avoid future breaking changes from this package.

Replaced discontinued shim from social-auth-app-django

---

applications/forms.py
applications/templates/applications/application_success_mail.txt
applications/tests.py
applications/views.py

Fixes #567 
Group choice priorities are now included in the application confirmation email.

Include group choice priorities in application confirmation email

---

committees/admin.py
inventory/admin.py
reservations/admin.py
website/models.py

Solves #571 
Adds search functionality to the standard select widget for user fields on the admin sites Committees, ItemLoans and Reservations. Utilizes the `autocomplete_fields` property.

Add search to user select on admin site

---

reservations/serializers.py
reservations/templates/reservations/queue_detail.html
reservations/views.py

Closes #558 and closes #417
- All reservations are now validated with `ReservationsSerializer`, with the proper rules for non-member.
- The user-attribute has also been moved from the request to the serializer, to prevent someone from reserving for someone else.
- Finally, the PATCH request method now only allows updating the reservation comment attribute. Originally, this method could be used to circumvent all validation and change any attribute of a reservation 🤡
- Oh, and full calendar has received some refactoring and fixes

Fix reservations validation and fullcalendar

---

files/static/files/js/gallery.js
files/templates/files/images-modal.html
files/templates/files/images.html

Images are sorted by categories, but each category can be rather large and it takes a long time to scroll through the whole page.
With this change, all categories are collapsible with the collapsible feature from Materialize.
closes: #579

Made image categories collapsible

---

files/templates/files/images-modal.html

Added a delete button in images-modal.html which removes the selected thumbnail.
Thumbnails that can be deleted include thumbnails for items, articles, events, and soon projects.
closes: #566

Delete button for thumbnails added

---

requirements.txt

Closes #601 
Django version is now fixed to 3.0 (and compatible minor releases), since the newly released Django 4.0 has breaking changes. These can be taken care of in the future if we choose to upgrade to 4.0.

Fix django version to ~3.0

---

userprofile/views.py

Closes #600 
Some previous refactoring with flake8 caused a 'try-except' to be removed. Without this, an error was thrown if no skill id was provided in the request url. This should be optional, so a simple if check has been added to fix this.

Fix skills page direct id handling (#600)

---

news/event_urls.py
news/ical.py
news/templates/news/event.html
requirements.txt

Per Magnus sitt ønske i #dev-public. Legger til en knapp til alle arrangementer for å laste ned en kalenderfil for det arrangementet. Det er også en skjult lenke (dvs. uten knapp/lenke på nettsiden) som lar deg laste ned en feed som inneholder alle arrangementer (/events/feed.ics)

Add iCalendar feeds for arrangements

---

website/templates/website/_social_buttons.html

As suggested by Kristian Skåland in #dev-public. The Instagram presence is heavily outdated (the latest post is from May 2019), and this will probably not change in the foreseeable future.

Remove Instagram badge on front-page

---

.github/workflows/integration.yml

Closes #616 
The Python Integration workflow currently runs twice for pull requests. With this change, integration will only run on pull requests, and on pushes to master. The latter is to ensure that the integration check is also run after merge to master.
Deduplication is visible in this pull request, as only one check instance runs.

Deduplicate integration workflow on pull requests

---

news/ical.py

`/events/feed.ics` gives 500 error since some events don't have a value for the `responsible` user field. Fixed this by adding a simple existence check.

Hotfix: Add event responsible exists check

---

userprofile/models.py

Closes #660 
Main group was determined as the first `Group` associated with a user. This has now been changed to the first `Group` associated with a user **which is also** a `Committee`, with fallback to any first `Group `.

Fix user main group

---

userprofile/forms.py
userprofile/views.py

Closes #541 
This stops a user from removing their registered phone number if they have an ongoing or future reservation (checks if reservation `end` is after current time).

Enforce phone number requirement with ongoing or future reservations

---

files/templates/files/_upload_modal.html

Temporarily addresses #668
The image modal template tag does not seem to have access to context processors. So for now the context processor tag has been replaced with the hard-coded value. Should look into how to access context processors in template tags, or convert modals to actual templates.

Add temporary image upload fix

---

website/templates/website/about.html

Closes #673 
This makes urls (and emails) in the group descriptions clickable. Custom hyperlink text is still not supported. See [Django docs for urlize](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#urlize) for more info.

Clickable urls in group descriptions

---

projectarchive/templates/projectarchive/_list_admin_banner.html
projectarchive/templates/projectarchive/article.html

in the edited files was `perms.projectarticle` referenced instead of the correct `perms.projectarchive`. This removed the administrator panel for those with correct permission.

change permissions in html for projectarchive

---

watchlist/static/watchlist/css/watchlist.css
watchlist/templates/watchlist/watchlist.html

Change cursor to pointer when hovering over watchlist icons that show a modal when clicked on

---

.pre-commit-config.yaml

The flake8 repo has been moved from gitlab to github which prevented it to be used. Which repository pre-commit gets flake8 from is now changed in the pre-commit config file.

updated pre-commit from gitlab to github

---

news/static/news/css/news_style.css

La til automatisk høyde på progress bar i påmelding. Materialize css hadde en oppdatering som gjorde at dette ble nødvendig. 
Closes: #701

la til automatisk høyde på progress bar

---

news/static/news/css/news_style.css

closes: #710 
Fixed a bug where the information about number of people registered for an event was hidden behind the progress bar.
This is fixed with setting the p tag in the progress bar to have a relative position.

add relative position to p tag in progress

---

.github/workflows/deploy.yml

The deploy script fails each time it is run because a sudo command is run. Sudo requires password input from standard input which is not given to it. The `sudo systemctl restart gunicorn` command is switched to `echo "${{ secrets.dingseboms_password }}" | sudo -S systemctl restart gunicorn`. Here means `-S` to read from standard output which echo prints to.

added password to sudo command in deploy

---

website/templates/website/_social_buttons.html
website/templates/website/index.html

- Moved 'SØK HACKERSPACE' button to _social_buttons header and restyled it.
- Changed the layout of the _social_buttons to scale reasonably for different width screens.
- Added django template check to ensure that the 'SØK HACKERSPACE' button is not shown for active members.

738 make search hackerspace btn accessible

---

.gitignore
inventory/views/item_loan.py

made loan application search case-insensitive

---

internalportal/apps.py
internalportal/templates/internalportal/internalportal.html
internalportal/urls.py
internalportal/views.py
website/settings.py
website/templates/website/header.html
website/urls.py
website/views.py

Moved internalportal to separate app

---

news/ical.py

Fixes bug where ical download crashed because of several responsible people. This has now been changed to join the responsible people to a list of people

make organization to list of responsible

---

files/locale/en/LC_MESSAGES/django.po
files/locale/nb/LC_MESSAGES/django.po
files/templates/files/image_confirm_delete.html
inventory/locale/en/LC_MESSAGES/django.po
inventory/locale/nb/LC_MESSAGES/django.po
inventory/views/item_loan.py
news/locale/en/LC_MESSAGES/django.po
news/locale/nb/LC_MESSAGES/django.po
news/templates/news/event_confirm_delete.html
projectarchive/locale/en/LC_MESSAGES/django.po
projectarchive/locale/nb/LC_MESSAGES/django.po
website/locale/en/LC_MESSAGES/django.po
website/locale/nb/LC_MESSAGES/django.po
website/templatetags/includeslots.py

Adds several forgotten translations.
Adds d.m.y as an accepted format. It is assumed on Norwegian, but on the English version it has to be added explicitly.
Not really the best solution, but I just want this to work

updates locales and add date supported formats
