hackerspace-ntnu/website

login/admin.py, login/apps.py, login/forms.py, login/models.py, login/templates/login.html, login/tests.py, login/urls.py, login/views.py, website/settings/__init__.py, website/static/css/loginform.css, website/static/js/loginform.js, website/templates/base.html, website/urls.py, website/views.py
Adds a loginform to the main page
=> Add loginform

README.md
removed beta. from the url in the README :)
=> Update README to point to the new url

news/forms.py, news/models.py, news/templates/edit_article.html, news/templates/edit_event.html, news/templates/event.html, news/templates/news.html, news/views.py, website/views.py
Vi kan endelig gjøre artikkler og events interne yay me, \o/
=> Interne events og artikler, fordi det er den handler om

inventory/static/inventory/css/style.css, inventory/templates/inventory/administrate_loans.html, inventory/templates/inventory/index.html, inventory/tests.py, inventory/views.py
=> Inventory updates

website/templates/index.html, website/urls.py, website/views.py
Denne er basert på riktig branch :-)
=> Add cookie warning EU functionality on front page

userprofile/templates/members.html, userprofile/views.py
=> Userprofile fixy fixy 2.0

committees/forms.py, committees/models.py, committees/templates/committees/edit_committee.html, committees/templates/committees/edit_members.html, committees/templates/committees/list_committees.html, committees/templates/committees/view_committee.html, committees/views.py
Fix upload of new picture to make it consistent with news and events
=> Com image form

website/templates/index.html, website/urls.py, website/views.py
Fjernet all cookie warning / EU greier da vi ikke trenger det alikevel.
=> Remove cookies, not needed for our useage

.gitignore
Irriterende når rope project files dukker opp i git.
=> Add rope project files to gitignore

committees/views.py
=> Protect edit views for committees.

news/templates/news/events.html, userprofile/templates/userprofile/edit_profile.html
=> Hotfix newslist

news/templates/news/events.html, news/templates/news/news.html
=> Fix listing of events

userprofile/templates/userprofile/members.html, userprofile/templates/userprofile/skill.html
oppdatere userprofile URL paths til å benytte user id istedenfor profile id.
=> Update userprofile paths

authentication/templates/authentication/signup.html
=> Add link to tos

website/templates/website/index.html
=> Fjern opptaksbanner på nettsiden

news/templates/news/article.html, website/templates/website/index.html
=> opptak fjern

committees/templates/committees/list_committees.html, committees/templates/committees/view_committee.html
Links are now actually viewable. Fixes #223
=> Fix committees links

website/templates/website/base.html
Materialize 1.0.0 Release er ute. Ikke mer beta eller rc :) :sparkles:
=> Oppdater til materialize release

website/templates/website/index.html, website/views.py
Legg til banner som vises når applications er åpnet.
=> Add front page index.html logic for new application date system

website/templates/website/index.html, website/urls.py, website/views.py
=> Fjern chritmas, gjør om til class based views, oppdater fra url til path

authentication/urls.py, authentication/views.py, userprofile/views.py
=> Clean up userprofile and authentication for better generics

news/templates/news/event.html
Add button as requested in #157
=> Add login button if event reg and not logged in

news/templates/news/article.html, news/templates/news/event.html, website/settings.py
Use responsive-img instead of home made stuff for images other than mobile devices.
Fixes #258
=> Fix image resize bugs, keep ratio, allow image uploads 

website/templates/website/about.html
Nestleder står som økonomiansvarlig i "om oss" siden
=> Fix economy name in template

website/static/website/css/style.css, website/templates/website/index.html
Last inn bilde fra slide 1 som background-image med transparency over dekkende objekter for en smoothere transition
=> Fix slideshow loading pretty

news/models.py, website/templates/website/index.html, website/views.py
=> New badges in events

userprofile/views.py
Legg til filtrering på grupper istedenfor den gamle "member" gruppen.
=> Add filtering on all members in committees

userprofile/views.py
Fixes broken and duplicate members in list
=> Order by first name

news/templates/news/edit_article.html, news/templates/news/edit_event.html, userprofile/templates/userprofile/edit_profile.html, userprofile/templates/userprofile/profile.html, userprofile/templates/userprofile/profile_list.html
=> Tweak stylings and error messages

website/templates/website/about.html
=> Better styling of groups

news/templates/news/event.html
Add angel/devil icon depending on if person met or not.
=> Add icons to indicate if attended or not

authentication/tests.py, authentication/urls.py, authentication/views.py, news/forms.py, news/templates/news/event.html, requirements.txt, website/settings.py, website/templates/website/header.html, website/urls.py
Gå vekk fra gammel dataporten oauth og legg inn python social auth systemet
=> New authentication system

website/urls.py
Dette bør rette feilen beskrevet i #358
=> Override ckeditor_upload urls with better permissions

website/templates/website/footer.html
Fikset logg inn knapp i footer + lagt til logg ut knapp i footer hvis noen er logget inn.
Fixes: #416
=> fikset logg inn link i footer

.github/workflows/deploy.yml
=> add deployment logic

news/templates/news/article.html, news/views.py
=> Added previous/next article section

website/templates/website/index.html, website/views.py
=> Filtered indicator count to upcoming events

news/views.py, website/templates/website/base.html
Fixes: #442 
Other:
- Replaced hard-coded `25` with message level constant `messages.SUCCESS`
=> Added log-in prompt on access denied

website/templates/website/header.html
=> Updated map link in header menu

userprofile/views.py, website/urls.py
=> Removed editing capabilities to enforce revision tracking

news/templates/news/_event_admin_menu.html
Applies the improved styling on attendees of events in the future (those with hourglass icons). This was simply forgotten in the previous push.
=> Hotfix to include improved attendee styling on future events

website/urls.py
=> Revert "Improved API url construction"

website/views.py
Fixes #477 
Also redirected non-users and users that already accept the most recent TOS.
=> Redirect users already accepting TOS and avoid storing invalid referral link

userprofile/templates/userprofile/profile.html, userprofile/templates/userprofile/skills.html
Fixed some mix-up between user id and profile id in the links related to profile skills
=> Fixed wrong user id in profile and skills links

website/templates/website/about.html
Fixes #483 
If no email is registered for the committee, the button will be hidden and no email displayed in popup
=> Added no email check on committee about page

userprofile/templates/userprofile/skill_description.html, userprofile/templates/userprofile/skills.html, website/static/website/css/style.css, website/templates/website/about.html
Defined a new divider class to be used (initially) between committee buttons (on about page) and approve button and prerequisites list (on skills page). Also flattened skill approve button
=> Added extra divider and refined skill approve button

news/models.py, news/static/news/css/news_style.css, news/templates/news/_event_admin_menu.html, userprofile/models.py
Replaced simple allergies count with profile names and associated food preferences
=> DRAFT: Added profile names in allergies section

news/views.py
=> Set initial (de)registration end in one week

news/forms.py, news/models.py, news/templates/news/_list_admin_banner.html, website/templates/website/footer.html, website/templates/website/header.html, website/templates/website/index.html
Collection of grammar enhancements and minor text changes
=> Grammar enhancements

inventory/views.py
et ekte 🐒⌨️-øyeblikk
Arverekkefølgen på views har noe å si. PermissionRequiredMixin må komme først ellers gjør det ikke en drit
=> Fix auth being neglected for loan views

website/static/website/css/style.css, website/templates/website/header.html
Herpa på mobil men der er jo allerede bildegalleriet erstattet av coglight. Så...🔨 💥
=> Remove coglight from navbar on mobile

README.md
Instructions were antiquated. Updated to reflect current best practices.
=> Update venv instructions to reflect current method

watchlist/models.py, watchlist/templates/watchlist/watchlist.html
Fikser strengformatering av vaktblokkmodellen og at modalen ikke dukker opp på mobil
=> Vaktliste hotfix

watchlist/utils.py
=> VAKTLISTE COLDFIX

watchlist/templates/watchlist/_watchlist_admin_banner.html, watchlist/templates/watchlist/watchlist.html, watchlist/urls.py, watchlist/views.py
=> Watchlist improvements

website/templates/website/intranet.html, website/views.py
fikser feil rekkefølge og strikethrough på arrangementer som ikke engang har starta enda
aka dette
=> Liten intranettfiks for arrangementer

applications/templates/applications/application_form.html, files/templates/files/_file_widget.html, inventory/migrations/0014_itemloan.py, inventory/models.py, news/forms.py, userprofile/forms.py, userprofile/migrations/0015_auto_20190505_2344.py, userprofile/models.py, userprofile/templates/userprofile/edit_profile.html, userprofile/views.py, website/templates/website/about.html
Solves #540
Added "clearable" image input. Uses same widget as file uploads for events.
Oh, and `epost -> e-post`
=> Ability to remove uploaded profile picture

website/templates/website/header.html
La til opptak på dropdown meny
=> La til opptak på dropdown meny

website/templates/website/_application_banner.html, website/templates/website/header.html
=> Endret opptaksbanner

inventory/templates/inventory/items_list.html
=> Add loan button to inventory item list

userprofile/static/userprofile/css/userprofile_style.css, userprofile/templates/userprofile/profile.html
=> Fix mobile style on profile page

news/templates/news/_event_admin_menu.html, news/views.py
=> Fix "no food preferences" message

.github/workflows/integration.yml
Closes #599 
This checks if contributions actually follow pre-commit rules.
=> Replace flake8 with pre-commit hooks in Github Actions

news/event_urls.py, news/ical.py, news/templates/news/event.html, requirements.txt
=> no u "Revert "Add iCalendar feeds for arrangements""

.github/workflows/deploy.yml, .github/workflows/integration.yml
Ensures the latest packages matching dependency requirements
=> Force pip dependencies reinstall when deploying

website/templates/website/_social_buttons.html
A request from Eskil to reintroduce the Instagram link. Hopefully it will last.
=> feat(_social_buttons): instagram is back

news/templates/news/_event-list-element.html, news/templates/news/article_item.html, projectarchive/templates/projectarchive/article_item.html, website/templates/website/_default_img.html
=> Added default image to news

website/templates/website/header.html, website/templates/website/intranet.html
Added icons to menu items, for both desktop and mobile.
-|-|-
Also updated icons for "Internportal" to be consistent with the menus
=> Add menu icons

news/views.py
=> Fix events order to be consistent with front page

.gitignore, news/admin.py, news/models.py, projectarchive/models.py, reservations/models.py, search/admin.py, search/apps.py, search/models.py, search/static/search/css/view.css, search/static/search/javascript/live_search.js, search/templates/search/item/article.html, search/templates/search/item/event.html, search/templates/search/item/faq.html, search/templates/search/item/projectarticle.html, search/templates/search/item/queue.html, search/templates/search/item/rule.html, search/templates/search/item/user.html, search/templates/search/search_item.html, search/templates/search/search_results.html, search/templates/search/view.html, search/templatetags/add_date.py, search/templatetags/class_name.py, search/tests.py, search/views.py, userprofile/models.py, website/models.py, website/settings.py, website/templates/website/header.html, website/urls.py
Closes #112 
Implemeterer søkefunksjonalitet som henter resultater fra:
- Artikler
- Prosjektarkiv
- Arrangementer
- Profiler
- Reservasjonskøer
- Ofte stilte spørsmål
- Regler
=> Globalt søk

website/admin.py
Added Django's log entry model to display in the admin page. Django logs this information from before and will therefore be populated already when implemented. Possible to filter by groups and search by users first name and last name,
=> Log entries in admin

news/static/news/css/news_style.css, news/templates/news/article.html, projectarchive/static/projectarchive/css/projectarchive_style.css
just made that picture`s max width is 600 (the grenseverdi)
closes: #697
=> issue 697 maximum width for image on background

userprofile/templates/userprofile/profile.html, userprofile/templates/userprofile/skills.html, watchlist/templates/watchlist/watchlist.html
changed the skill circles to checkmarks from 0 and 1. Also removed hover.
Changed files skills, profile in dir userprofile
Changed files watchlist in dir watchlist
closes: #702
=> Added checkmarks to skills

news/static/news/css/news_style.css, news/templates/news/_event_admin_menu.html
closes: #718 
Adding styling to list element with flex row and justify-content: space-between
=> set flex on list with space-between

applications/templates/applications/application_success_mail.txt, applications/tests.py
Changed the text on the submission mail to better fit current circumstance. 
closes: #744
=> updatet submission success mail

inventory/templates/inventory/itemloan_late_retrieval_mail.txt, requirements.txt, website/inventory_late_poker.py, website/settings.py
=> ny crontab branch fordi fuck git

website/locale/en/LC_MESSAGES/django.po, website/locale/nb/LC_MESSAGES/django.po
closes partly #649 
Uses LabOps' translations for parts of the website. Lots of the website is hardcoded in backend and this does not update that.
New English translations need to be made later.
=> english translation from labops magic

applications/views.py
Fixes an issue where new applicants are still able to choose groups which are not open for applications.
=> fix(applications): filter applications 

files/templates/files/image_confirm_delete.html
=> Fixed image gallery deletion error

applications/templates/applications/new_application_email.txt, internalportal/templates/internalportal/application.html, internalportal/templates/internalportal/applications/next_group.html, internalportal/urls.py, internalportal/views.py
Creates a new view which sends an application to the next group.
Modifies permissions to also give access to superusers
=> feat(internalportal): send application to next group in priority

inventory/templates/inventory/edit_item.html
Fixes bug where inventory/new crashed because "load i18n" tag was not in the file
=> add load i18n to inventory
